// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220605112723_add-ilceler")]
    partial class addilceler
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("WebApi.Entities.IletisimBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Boylam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enlem")
                        .HasColumnType("TEXT");

                    b.Property<int>("Il")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ilce")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MagzaAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IletisimBilgileri");
                });

            modelBuilder.Entity("WebApi.Entities.ilceler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ilceadi")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("sehirid")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ilceler");
                });

            modelBuilder.Entity("WebApi.Entities.iller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("sehiradi")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("iller");
                });
#pragma warning restore 612, 618
        }
    }
}
