// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("WebApi.Entities.IletisimBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcikAdres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Boylam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enlem")
                        .HasColumnType("TEXT");

                    b.Property<int>("Il")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ilce")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MagzaAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
